# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1126, 824)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("source/DataYee.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setDockOptions(QtWidgets.QMainWindow.AllowNestedDocks|QtWidgets.QMainWindow.AllowTabbedDocks|QtWidgets.QMainWindow.AnimatedDocks)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(20, 50, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton { color: black;}")
        self.pushButton.setObjectName("pushButton")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(260, 0, 851, 581))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setUnderline(False)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.leftButton = QtWidgets.QPushButton(self.centralwidget)
        self.leftButton.setGeometry(QtCore.QRect(660, 640, 90, 51))
        self.leftButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("source/left_arrow.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.leftButton.setIcon(icon1)
        self.leftButton.setIconSize(QtCore.QSize(60, 60))
        self.leftButton.setObjectName("leftButton")
        self.lcslide = QtWidgets.QSlider(self.centralwidget)
        self.lcslide.setGeometry(QtCore.QRect(400, 640, 160, 22))
        self.lcslide.setMinimum(-50)
        self.lcslide.setMaximum(50)
        self.lcslide.setProperty("value", 0)
        self.lcslide.setTracking(True)
        self.lcslide.setOrientation(QtCore.Qt.Horizontal)
        self.lcslide.setObjectName("lcslide")
        self.lpslide = QtWidgets.QSlider(self.centralwidget)
        self.lpslide.setGeometry(QtCore.QRect(400, 690, 160, 22))
        self.lpslide.setMinimum(-20)
        self.lpslide.setMaximum(20)
        self.lpslide.setPageStep(10)
        self.lpslide.setProperty("value", 0)
        self.lpslide.setOrientation(QtCore.Qt.Horizontal)
        self.lpslide.setObjectName("lpslide")
        self.trashButtom = QtWidgets.QPushButton(self.centralwidget)
        self.trashButtom.setGeometry(QtCore.QRect(1020, 590, 71, 71))
        self.trashButtom.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("source/trash.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.trashButtom.setIcon(icon2)
        self.trashButtom.setIconSize(QtCore.QSize(60, 60))
        self.trashButtom.setObjectName("trashButtom")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(260, 570, 851, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(640, 580, 371, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lcdoubleSpinBox = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.lcdoubleSpinBox.setGeometry(QtCore.QRect(320, 630, 70, 30))
        self.lcdoubleSpinBox.setDecimals(1)
        self.lcdoubleSpinBox.setSingleStep(0.5)
        self.lcdoubleSpinBox.setProperty("value", 1.0)
        self.lcdoubleSpinBox.setObjectName("lcdoubleSpinBox")
        self.lpdoubleSpinBox = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.lpdoubleSpinBox.setGeometry(QtCore.QRect(320, 680, 70, 30))
        self.lpdoubleSpinBox.setMaximum(0.1)
        self.lpdoubleSpinBox.setSingleStep(0.005)
        self.lpdoubleSpinBox.setProperty("value", 0.01)
        self.lpdoubleSpinBox.setObjectName("lpdoubleSpinBox")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(280, 630, 41, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(280, 680, 41, 31))
        self.label_3.setObjectName("label_3")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(620, 580, 16, 181))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(1000, 580, 20, 181))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(1020, 670, 71, 71))
        self.pushButton_2.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("source/renew.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon3)
        self.pushButton_2.setIconSize(QtCore.QSize(60, 60))
        self.pushButton_2.setObjectName("pushButton_2")
        self.rightButton = QtWidgets.QPushButton(self.centralwidget)
        self.rightButton.setGeometry(QtCore.QRect(840, 640, 90, 51))
        self.rightButton.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("source/right.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rightButton.setIcon(icon4)
        self.rightButton.setIconSize(QtCore.QSize(60, 60))
        self.rightButton.setObjectName("rightButton")
        self.radioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton.setGeometry(QtCore.QRect(20, 0, 161, 41))
        self.radioButton.setObjectName("radioButton")
        self.topButton = QtWidgets.QPushButton(self.centralwidget)
        self.topButton.setGeometry(QtCore.QRect(750, 620, 91, 51))
        self.topButton.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("source/top.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.topButton.setIcon(icon5)
        self.topButton.setIconSize(QtCore.QSize(60, 60))
        self.topButton.setObjectName("topButton")
        self.downButton = QtWidgets.QPushButton(self.centralwidget)
        self.downButton.setGeometry(QtCore.QRect(750, 670, 91, 51))
        self.downButton.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("source/down.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.downButton.setIcon(icon6)
        self.downButton.setIconSize(QtCore.QSize(60, 60))
        self.downButton.setObjectName("downButton")
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setGeometry(QtCore.QRect(1100, 580, 20, 181))
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_6 = QtWidgets.QFrame(self.centralwidget)
        self.line_6.setGeometry(QtCore.QRect(260, 750, 851, 16))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.lclplabel = QtWidgets.QLabel(self.centralwidget)
        self.lclplabel.setGeometry(QtCore.QRect(270, 580, 351, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lclplabel.setFont(font)
        self.lclplabel.setObjectName("lclplabel")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(250, 580, 20, 181))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.spinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox.setGeometry(QtCore.QRect(940, 650, 61, 31))
        self.spinBox.setMaximum(10000)
        self.spinBox.setSingleStep(10)
        self.spinBox.setObjectName("spinBox")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1126, 45))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.menuBar.setFont(font)
        self.menuBar.setObjectName("menuBar")
        self.menu = QtWidgets.QMenu(self.menuBar)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.menu.setFont(font)
        self.menu.setObjectName("menu")
        self.menuOpen = QtWidgets.QMenu(self.menu)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.menuOpen.setFont(font)
        self.menuOpen.setStyleSheet("")
        self.menuOpen.setObjectName("menuOpen")
        self.menuExport = QtWidgets.QMenu(self.menu)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.menuExport.setFont(font)
        self.menuExport.setObjectName("menuExport")
        self.menuAbout = QtWidgets.QMenu(self.menuBar)
        self.menuAbout.setObjectName("menuAbout")
        self.menuEdit = QtWidgets.QMenu(self.menuBar)
        self.menuEdit.setObjectName("menuEdit")
        MainWindow.setMenuBar(self.menuBar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.LeftToolBarArea, self.toolBar)
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionForce_Curve = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.actionForce_Curve.setFont(font)
        self.actionForce_Curve.setObjectName("actionForce_Curve")
        self.actionBatch_of_Force_Curve = QtWidgets.QAction(MainWindow)
        self.actionBatch_of_Force_Curve.setCheckable(True)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.actionBatch_of_Force_Curve.setFont(font)
        self.actionBatch_of_Force_Curve.setObjectName("actionBatch_of_Force_Curve")
        self.actionSave_as = QtWidgets.QAction(MainWindow)
        self.actionSave_as.setObjectName("actionSave_as")
        self.actiontxt = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.actiontxt.setFont(font)
        self.actiontxt.setObjectName("actiontxt")
        self.actionexcel = QtWidgets.QAction(MainWindow)
        self.actionexcel.setObjectName("actionexcel")
        self.actionCreate_methods = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.actionCreate_methods.setFont(font)
        self.actionCreate_methods.setObjectName("actionCreate_methods")
        self.actionUndo = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.actionUndo.setFont(font)
        self.actionUndo.setObjectName("actionUndo")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionhelp = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.actionhelp.setFont(font)
        self.actionhelp.setObjectName("actionhelp")
        self.actionDataYee = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.actionDataYee.setFont(font)
        self.actionDataYee.setObjectName("actionDataYee")
        self.actionDataYee_Force = QtWidgets.QAction(MainWindow)
        self.actionDataYee_Force.setObjectName("actionDataYee_Force")
        self.actionDelete = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.actionDelete.setFont(font)
        self.actionDelete.setObjectName("actionDelete")
        self.actionBaseline_plus = QtWidgets.QAction(MainWindow)
        self.actionBaseline_plus.setObjectName("actionBaseline_plus")
        self.actionBaseline_minus = QtWidgets.QAction(MainWindow)
        self.actionBaseline_minus.setObjectName("actionBaseline_minus")
        self.menuOpen.addSeparator()
        self.menuOpen.addAction(self.actionForce_Curve)
        self.menuOpen.addAction(self.actionBatch_of_Force_Curve)
        self.menuOpen.addAction(self.actionDataYee_Force)
        self.menuExport.addAction(self.actiontxt)
        self.menuExport.addAction(self.actionexcel)
        self.menu.addAction(self.menuOpen.menuAction())
        self.menu.addAction(self.actionSave)
        self.menu.addAction(self.actionSave_as)
        self.menu.addAction(self.menuExport.menuAction())
        self.menu.addSeparator()
        self.menu.addAction(self.actionExit)
        self.menuAbout.addAction(self.actionhelp)
        self.menuAbout.addAction(self.actionDataYee)
        self.menuEdit.addAction(self.actionDelete)
        self.menuEdit.addAction(self.actionBaseline_plus)
        self.menuEdit.addAction(self.actionBaseline_minus)
        self.menuBar.addAction(self.menu.menuAction())
        self.menuBar.addAction(self.menuEdit.menuAction())
        self.menuBar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "DataYee"))
        self.pushButton.setText(_translate("MainWindow", "Run"))
        self.groupBox.setTitle(_translate("MainWindow", "Force Curve"))
        self.label.setText(_translate("MainWindow", "Peak select:"))
        self.label_2.setText(_translate("MainWindow", "Lc"))
        self.label_3.setText(_translate("MainWindow", "Lp"))
        self.radioButton.setText(_translate("MainWindow", "FAST MODEL"))
        self.lclplabel.setText(_translate("MainWindow", "Arg:"))
        self.menu.setTitle(_translate("MainWindow", "File"))
        self.menuOpen.setTitle(_translate("MainWindow", "Open"))
        self.menuExport.setTitle(_translate("MainWindow", "Export"))
        self.menuAbout.setTitle(_translate("MainWindow", "About"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionForce_Curve.setText(_translate("MainWindow", "Force Curve"))
        self.actionBatch_of_Force_Curve.setText(_translate("MainWindow", "Batch of Force Curve"))
        self.actionBatch_of_Force_Curve.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionSave_as.setText(_translate("MainWindow", "Save as"))
        self.actiontxt.setText(_translate("MainWindow", "txt"))
        self.actionexcel.setText(_translate("MainWindow", "excel"))
        self.actionCreate_methods.setText(_translate("MainWindow", "Methods"))
        self.actionUndo.setText(_translate("MainWindow", "Undo"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionhelp.setText(_translate("MainWindow", "help"))
        self.actionDataYee.setText(_translate("MainWindow", "DataYee"))
        self.actionDataYee_Force.setText(_translate("MainWindow", "DataYee-Force"))
        self.actionDelete.setText(_translate("MainWindow", "Delete"))
        self.actionDelete.setShortcut(_translate("MainWindow", "Del"))
        self.actionBaseline_plus.setText(_translate("MainWindow", "Baseline plus"))
        self.actionBaseline_plus.setShortcut(_translate("MainWindow", "Ctrl+="))
        self.actionBaseline_minus.setText(_translate("MainWindow", "Baseline minus"))
        self.actionBaseline_minus.setShortcut(_translate("MainWindow", "Ctrl+-"))

