# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'parameters.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(617, 342)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(250, 290, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(40, 100, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(90, 160, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(70, 220, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.sens = QtWidgets.QDoubleSpinBox(Dialog)
        self.sens.setGeometry(QtCore.QRect(220, 100, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.sens.setFont(font)
        self.sens.setMaximum(500.0)
        self.sens.setSingleStep(1.0)
        self.sens.setProperty("value", 10.0)
        self.sens.setObjectName("sens")
        self.xlimit = QtWidgets.QDoubleSpinBox(Dialog)
        self.xlimit.setGeometry(QtCore.QRect(220, 160, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.xlimit.setFont(font)
        self.xlimit.setMaximum(1000.0)
        self.xlimit.setSingleStep(5.0)
        self.xlimit.setProperty("value", 20.0)
        self.xlimit.setObjectName("xlimit")
        self.xsens = QtWidgets.QDoubleSpinBox(Dialog)
        self.xsens.setGeometry(QtCore.QRect(220, 220, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.xsens.setFont(font)
        self.xsens.setProperty("value", 2.0)
        self.xsens.setObjectName("xsens")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(320, 110, 72, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(320, 180, 72, 15))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(320, 240, 72, 15))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(40, 40, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.peakH = QtWidgets.QDoubleSpinBox(Dialog)
        self.peakH.setGeometry(QtCore.QRect(220, 40, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.peakH.setFont(font)
        self.peakH.setMaximum(500.0)
        self.peakH.setSingleStep(5.0)
        self.peakH.setProperty("value", 30.0)
        self.peakH.setObjectName("peakH")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(320, 50, 72, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.highspeed = QtWidgets.QRadioButton(Dialog)
        self.highspeed.setGeometry(QtCore.QRect(400, 40, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.highspeed.setFont(font)
        self.highspeed.setObjectName("highspeed")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Force sensitivity"))
        self.label_2.setText(_translate("Dialog", "X limit"))
        self.label_3.setText(_translate("Dialog", "X sensitivity"))
        self.label_4.setText(_translate("Dialog", "pN"))
        self.label_5.setText(_translate("Dialog", "nm"))
        self.label_6.setText(_translate("Dialog", "nm"))
        self.label_7.setText(_translate("Dialog", "Force threshold"))
        self.label_8.setText(_translate("Dialog", "pN"))
        self.highspeed.setText(_translate("Dialog", "High Speed"))

