# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fittingEnergy.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_fitting(object):
    def setupUi(self, fitting):
        fitting.setObjectName("fitting")
        fitting.resize(674, 493)
        self.gridLayout = QtWidgets.QGridLayout(fitting)
        self.gridLayout.setObjectName("gridLayout")
        self.graphicsView = QtWidgets.QGraphicsView(fitting)
        self.graphicsView.setMinimumSize(QtCore.QSize(400, 0))
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayout.addWidget(self.graphicsView, 0, 0, 1, 3)
        self.tableWidget = QtWidgets.QTableWidget(fitting)
        self.tableWidget.setMinimumSize(QtCore.QSize(0, 400))
        self.tableWidget.setMaximumSize(QtCore.QSize(450, 16777215))
        self.tableWidget.setRowCount(15)
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        self.tableWidget.horizontalHeader().setVisible(False)
        self.tableWidget.horizontalHeader().setHighlightSections(True)
        self.tableWidget.verticalHeader().setVisible(False)
        self.gridLayout.addWidget(self.tableWidget, 0, 3, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(fitting)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox_2)
        self.formLayout.setObjectName("formLayout")
        self.pushButton = QtWidgets.QPushButton(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.pushButton_2)
        self.gridLayout.addWidget(self.groupBox_2, 1, 2, 1, 2)
        self.groupBox = QtWidgets.QGroupBox(fitting)
        self.groupBox.setMinimumSize(QtCore.QSize(400, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.groupBox.setFont(font)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout.addWidget(self.groupBox, 1, 1, 1, 1)

        self.retranslateUi(fitting)
        QtCore.QMetaObject.connectSlotsByName(fitting)

    def retranslateUi(self, fitting):
        _translate = QtCore.QCoreApplication.translate
        fitting.setWindowTitle(_translate("fitting", "Energy landscape"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("fitting", "Force (pN)"))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("fitting", "loading rate (pN/s)"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.pushButton.setText(_translate("fitting", "Calculate"))
        self.pushButton_2.setText(_translate("fitting", "Save"))
